const START_GAME = "START_GAME";
const END_GAME = "END_GAME";
const PAUSE_GAME = "PAUSE_GAME";

const SWITCH_PLAYER = "SWITCH_PLAYER";
const ADD_HISTORY = "ADD_HISTORY";

const START_TIMER = "START_TIMER";
const STOP_TIMER = "STOP_TIMER";
const SET_TIMER = "SET_TIMER";
const RESET_TIME = "RESET_TIME";
const TIME_TICK = "TIME_TICK";

export {
    START_GAME,
    END_GAME,
    PAUSE_GAME,
    SWITCH_PLAYER,
    ADD_HISTORY,
    START_TIMER,
    STOP_TIMER,
    SET_TIMER,
    RESET_TIME,
    TIME_TICK
};
